name: Mirror Repository

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  mirror:
    name: Mirror Repository to GitLab
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@v0.7.0
        with:
          REMOTE: 'ssh://git@gitlab.com/mbackonja1/mirror.git'
          PUSH_ALL_REFS: 'false'
          GIT_PUSH_ARGS: ' '
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          GIT_SSH_NO_VERIFY_HOST: 'true'
